# Generated by Django 3.0.5 on 2020-04-10 04:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Date Published')),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('user', models.CharField(max_length=50)),
                ('DodoCode', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Date Published')),
                ('item', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
