# Generated by Django 3.0.5 on 2020-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='DodoCode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
