# Generated by Django 3.0.5 on 2020-04-11 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0002_trade_dodocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalk',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date Published'),
        ),
    ]
