# Generated by Django 3.0.5 on 2020-04-11 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0003_auto_20200410_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalk',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published'),
        ),
    ]
