# Generated by Django 3.0.5 on 2020-04-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0004_auto_20200410_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalk',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
