# Generated by Django 3.0.5 on 2020-04-16 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0005_stalk_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalk',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Published'),
        ),
        migrations.AlterField(
            model_name='stalk',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 22, 26, 53, 399993), verbose_name='Date Published'),
        ),
    ]
