# Generated by Django 3.0.5 on 2020-04-16 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0006_auto_20200415_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalk',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 15), verbose_name='Date Published'),
        ),
    ]
