# Generated by Django 3.0.5 on 2020-04-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0007_auto_20200415_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stalk',
            old_name='time',
            new_name='pub_time',
        ),
    ]
