# Generated by Django 3.0.5 on 2020-04-16 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0008_auto_20200415_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Published'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 15), verbose_name='Date Published'),
        ),
    ]
