# Generated by Django 3.0.5 on 2020-04-16 17:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0009_auto_20200415_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalk',
            name='morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stalk',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 16), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='stalk',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Published'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 16), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Published'),
        ),
    ]
