# Generated by Django 3.0.5 on 2020-04-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0010_auto_20200416_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stalk',
            name='DodoCode',
        ),
        migrations.RemoveField(
            model_name='stalk',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='stalk',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stalk',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='stalk',
            name='pub_time',
        ),
        migrations.RemoveField(
            model_name='stalk',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='DodoCode',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='item',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pub_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
    ]
