# Generated by Django 3.0.5 on 2020-04-16 17:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stalkmarket', '0011_auto_20200416_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalk',
            name='DodoCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stalk',
            name='morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stalk',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stalk',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 16), verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='stalk',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Published'),
        ),
        migrations.AddField(
            model_name='stalk',
            name='user',
            field=models.CharField(default='p', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='DodoCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='item',
            field=models.CharField(default='iron', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 16), verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='trade',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Published'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.CharField(default='p', max_length=50),
            preserve_default=False,
        ),
    ]
